#from pybit.unified_trading import HTTP
import requests

from Invest_hub_b.scrt.keys import api_key, api_secret
import pandas as pd

trading_pairss = ['1INCHUSDT', 'AAVEUSDT', 'ACAUSDT', 'ACHUSDT', 'ACMUSDT', 'ADAUSDT', 'ADXUSDT', 'AERGOUSDT',
                  'AGIXUSDT', 'AGLDUSDT', 'AKROUSDT', 'ALCXUSDT', 'ALGOUSDT', 'ALICEUSDT', 'ALPACAUSDT', 'ALPHAUSDT',
                  'ALPINEUSDT', 'AMBUSDT', 'AMPUSDT', 'ANKRUSDT', 'ANTUSDT', 'APEUSDT', 'API3USDT', 'APTUSDT',
                  'ARBUSDT', 'ARDRUSDT', 'ARKMUSDT', 'ARPAUSDT', 'ARUSDT', 'ASRUSDT', 'ASTRUSDT', 'ASTUSDT', 'ATAUSDT',
                  'ATMUSDT', 'ATOMUSDT', 'AUCTIONUSDT', 'AUDIOUSDT', 'AVAUSDT', 'AVAXUSDT', 'AXSUSDT', 'BADGERUSDT',
                  'BAKEUSDT', 'BALUSDT', 'BANDUSDT', 'BARUSDT', 'BATUSDT', 'BCHUSDT', 'BELUSDT', 'BETAUSDT', 'BETHUSDT',
                  'BICOUSDT', 'BIFIUSDT', 'BLZUSDT', 'BNTUSDT', 'BNXUSDT', 'BONDUSDT', 'BSWUSDT', 'BTSUSDT', 'YGGUSDT',
                  'ZECUSDT', 'ZENUSDT', 'ZILUSDT', 'ZRXUSDT', 'BURGERUSDT', 'BUSDUSDT', 'C98USDT', 'CAKEUSDT',
                  'CELOUSDT', 'CELRUSDT', 'CFXUSDT', 'CHESSUSDT', 'CHRUSDT', 'CHZUSDT', 'CITYUSDT', 'CKBUSDT',
                  'CLVUSDT', 'COMBOUSDT', 'COMPUSDT', 'COSUSDT', 'COTIUSDT', 'CRVUSDT', 'CTKUSDT', 'CTSIUSDT',
                  'CTXCUSDT', 'CVCUSDT', 'CVPUSDT', 'CVXUSDT', 'CYBERUSDT', 'DARUSDT', 'DASHUSDT', 'DATAUSDT',
                  'DCRUSDT', 'DEGOUSDT', 'DENTUSDT', 'DEXEUSDT', 'DFUSDT', 'DGBUSDT', 'DIAUSDT', 'DOCKUSDT', 'DODOUSDT',
                  'DOGEUSDT', 'DOTUSDT', 'DREPUSDT', 'DUSKUSDT', 'DYDXUSDT', 'EDUUSDT', 'EGLDUSDT', 'ELFUSDT',
                  'ENJUSDT', 'ENSUSDT', 'EPXUSDT', 'ERNUSDT', 'ETCUSDT', 'EURUSDT', 'FARMUSDT', 'FDUSDUSDT', 'FETUSDT',
                  'FIDAUSDT', 'FILUSDT', 'FIOUSDT', 'FIROUSDT', 'FISUSDT', 'FLMUSDT', 'FLOKIUSDT', 'FLOWUSDT',
                  'FLUXUSDT', 'FORTHUSDT', 'FORUSDT', 'FRONTUSDT', 'FTMUSDT', 'FUNUSDT', 'FXSUSDT', 'GALAUSDT',
                  'GALUSDT', 'GASUSDT', 'GBPUSDT', 'GHSTUSDT', 'GLMRUSDT', 'GLMUSDT', 'GMTUSDT', 'GMXUSDT', 'GNOUSDT',
                  'GNSUSDT', 'GRTUSDT', 'GTCUSDT', 'HARDUSDT', 'HBARUSDT', 'HFTUSDT', 'HIFIUSDT', 'HIGHUSDT',
                  'HIVEUSDT', 'HOOKUSDT', 'HOTUSDT', 'ICPUSDT', 'ICXUSDT', 'IDEXUSDT', 'IDUSDT', 'ILVUSDT', 'IMXUSDT',
                  'INJUSDT', 'IOSTUSDT', 'IOTAUSDT', 'IOTXUSDT', 'IRISUSDT', 'JASMYUSDT', 'JOEUSDT', 'JSTUSDT',
                  'JUVUSDT', 'KAVAUSDT', 'KDAUSDT', 'KEYUSDT', 'KLAYUSDT', 'KMDUSDT', 'KNCUSDT', 'KP3RUSDT', 'KSMUSDT',
                  'LAZIOUSDT', 'LDOUSDT', 'LEVERUSDT', 'LINAUSDT', 'LINKUSDT', 'LITUSDT', 'LOKAUSDT', 'LOOMUSDT',
                  'LPTUSDT', 'LQTYUSDT', 'LRCUSDT', 'LSKUSDT', 'LTCUSDT', 'LTOUSDT', 'LUNAUSDT', 'LUNCUSDT',
                  'MAGICUSDT', 'MANAUSDT', 'MASKUSDT', 'MATICUSDT', 'MAVUSDT', 'MBLUSDT', 'MBOXUSDT', 'MCUSDT',
                  'MDTUSDT', 'MDXUSDT', 'MINAUSDT', 'MKRUSDT', 'MLNUSDT', 'MOBUSDT', 'MOVRUSDT', 'MTLUSDT', 'MULTIUSDT',
                  'NEARUSDT', 'NEOUSDT', 'NEXOUSDT', 'NKNUSDT', 'NMRUSDT', 'NULSUSDT', 'OAXUSDT', 'OCEANUSDT',
                  'OGNUSDT', 'OGUSDT', 'OMGUSDT', 'OMUSDT', 'ONEUSDT', 'ONGUSDT', 'ONTUSDT', 'OOKIUSDT', 'OPUSDT',
                  'ORNUSDT', 'OSMOUSDT', 'OXTUSDT', 'PAXGUSDT', 'PENDLEUSDT', 'PEOPLEUSDT', 'PERLUSDT', 'PERPUSDT',
                  'PHAUSDT', 'PHBUSDT', 'PLAUSDT', 'PNTUSDT', 'POLSUSDT', 'POLYXUSDT', 'PONDUSDT', 'PORTOUSDT',
                  'POWRUSDT', 'PROMUSDT', 'PROSUSDT', 'PSGUSDT', 'PUNDIXUSDT', 'PYRUSDT', 'QIUSDT', 'QKCUSDT',
                  'QNTUSDT', 'QTUMUSDT', 'QUICKUSDT', 'RADUSDT', 'RAREUSDT', 'RAYUSDT', 'RDNTUSDT', 'REEFUSDT',
                  'REIUSDT', 'RENUSDT', 'REQUSDT', 'RIFUSDT', 'RLCUSDT', 'RNDRUSDT', 'ROSEUSDT', 'RPLUSDT', 'RSRUSDT',
                  'RUNEUSDT', 'RVNUSDT', 'SANDUSDT', 'SANTOSUSDT', 'SCRTUSDT', 'SCUSDT', 'SEIUSDT', 'SFPUSDT',
                  'SHIBUSDT', 'SKLUSDT', 'SLPUSDT', 'SNTUSDT', 'SNXUSDT', 'SOLUSDT', 'SPELLUSDT', 'SSVUSDT',
                  'STEEMUSDT', 'STGUSDT', 'STMXUSDT', 'STORJUSDT', 'STPTUSDT', 'STRAXUSDT', 'STXUSDT', 'SUIUSDT',
                  'SUNUSDT', 'SUPERUSDT', 'SUSHIUSDT', 'SXPUSDT', 'SYNUSDT', 'SYSUSDT', 'TFUELUSDT', 'THETAUSDT',
                  'TKOUSDT', 'TLMUSDT', 'TOMOUSDT', 'TRBUSDT', 'TROYUSDT', 'TRUUSDT', 'TRXUSDT', 'TUSDT', 'TUSDUSDT',
                  'TVKUSDT', 'TWTUSDT', 'UFTUSDT', 'UMAUSDT', 'UNFIUSDT', 'UNIUSDT', 'USDCUSDT', 'USDPUSDT', 'USTCUSDT',
                  'UTKUSDT', 'VETUSDT', 'VGXUSDT', 'VIBUSDT', 'VIDTUSDT', 'VITEUSDT', 'VOXELUSDT', 'VTHOUSDT',
                  'WANUSDT', 'WAVESUSDT', 'WAXPUSDT', 'WBETHUSDT', 'WBTCUSDT', 'WINGUSDT', 'WINUSDT', 'WLDUSDT',
                  'WNXMUSDT', 'WOOUSDT', 'WRXUSDT', 'WTCUSDT', 'XECUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XNOUSDT',
                  'XRPUSDT', 'XVGUSDT', 'XVSUSDT', 'YFIUSDT']

trade_pairs_bybit = ['1INCHUSDT', '1SOLUSDT', '3PUSDT', '5IREUSDT', 'AAVEUSDT', 'ACAUSDT', 'ACHUSDT', 'ACMUSDT', 'ACSUSDT',
                   'ADA2LUSDT', 'ADA2SUSDT', 'ADAUSDT', 'AFCUSDT', 'AFGUSDT', 'AGIUSDT', 'AGIXUSDT', 'AGLAUSDT', 'AGLDUSDT',
                   'AIOZUSDT', 'AKIUSDT', 'ALGOUSDT', 'ANKRUSDT', 'APE2LUSDT', 'APE2SUSDT', 'APEUSDT', 'APEXUSDT', 'APPUSDT',
                   'APTUSDT', 'ARBUSDT', 'ARKMUSDT', 'ARTYUSDT', 'ARUSDT', 'ATOM2LUSDT', 'ATOM2SUSDT', 'ATOMUSDT', 'AVAUSDT',
                   'AVAX2LUSDT', 'AVAX2SUSDT', 'AVAXUSDT', 'AXLUSDT', 'AXSUSDT', 'AZYUSDT', 'BABYDOGEUSDT', 'BARUSDT', 'BATUSDT',
                   'BCHUSDT', 'BEAMUSDT', 'BELUSDT', 'BICOUSDT', 'BLURUSDT', 'BNBUSDT', 'BNTUSDT', 'BOBAUSDT', 'BOBUSDT', 'BONKUSDT',
                   'BTC3LUSDT', 'BTC3SUSDT', 'BTCUSDT', 'BTGUSDT', 'BTTUSDT', 'C98USDT', 'CAKEUSDT', 'CANDYUSDT', 'CAPOUSDT',
                   'CAPSUSDT', 'CATUSDT', 'CBKUSDT', 'CBXUSDT', 'CELOUSDT', 'CELUSDT', 'CGPTUSDT', 'CHRPUSDT', 'CHZUSDT', 'CITYUSDT',
                   'CMPUSDT', 'COMPUSDT', 'COMUSDT', 'COQUSDT', 'COREUSDT', 'COTUSDT', 'COUSDT', 'CRDSUSDT', 'CRVUSDT', 'CTCUSDT',
                   'CTTUSDT', 'CULTUSDT', 'CUSDUSDT', 'CWARUSDT', 'CYBERUSDT', 'DAIUSDT', 'DCRUSDT', 'DEFIUSDT', 'DEFYUSDT', 'DEVTUSDT',
                   'DFIUSDT', 'DGBUSDT', 'DICEUSDT', 'DLCUSDT', 'DMAILUSDT', 'DOGE2LUSDT', 'DOGE2SUSDT', 'DOGEUSDT', 'DOMEUSDT',
                   'DOT3LUSDT', 'DOT3SUSDT', 'DOTUSDT', 'DPXUSDT', 'DSRUNUSDT', 'DUELUSDT', 'DYDXUSDT', 'DZOOUSDT', 'ECOXUSDT',
                   'EGLDUSDT', 'EGOUSDT', 'ELDAUSDT', 'ELTUSDT', 'ENJUSDT', 'ENSUSDT', 'EOS2LUSDT', 'EOS2SUSDT', 'EOSUSDT', 'ERTHAUSDT',
                   'ETC2LUSDT', 'ETC2SUSDT', 'ETCUSDT', 'ETH3LUSDT', 'ETH3SUSDT', 'ETHUSDT', 'ETHWUSDT', 'EVERUSDT', 'FAMEUSDT',
                   'FARUSDT', 'FBUSDT', 'FETUSDT', 'FIDAUSDT', 'FILUSDT', 'FIREUSDT', 'FITFIUSDT', 'FLIPUSDT', 'FLOKIUSDT', 'FLOWUSDT',
                   'FLRUSDT', 'FMBUSDT', 'FMCUSDT', 'FONUSDT', 'FORTUSDT', 'FTM2LUSDT', 'FTM2SUSDT', 'FTMUSDT', 'FTTUSDT', 'FXSUSDT',
                   'GALAUSDT', 'GALFTUSDT', 'GALUSDT', 'GCAKEUSDT', 'GENEUSDT', 'GGMUSDT', 'GGUSDT', 'GLMRUSDT', 'GMT2LUSDT',
                   'GMT2SUSDT', 'GMTUSDT', 'GMUSDT', 'GMXUSDT', 'GNSUSDT', 'GODSUSDT', 'GPTUSDT', 'GRAPEUSDT', 'GRTUSDT',
                   'GSTSUSDT', 'GSTUSDT', 'GSWIFTUSDT', 'GTAIUSDT', 'HBARUSDT', 'HEROUSDT', 'HFTUSDT', 'HNTUSDT', 'HONUSDT',
                   'HOOKUSDT', 'HOTUSDT', 'HVHUSDT', 'ICPUSDT', 'ICXUSDT', 'IDUSDT', 'IMXUSDT', 'INJUSDT', 'INSPUSDT',
                   'INTERUSDT', 'IRLUSDT', 'IZIUSDT', 'JASMYUSDT', 'JEFFUSDT', 'JSTUSDT', 'JTOUSDT', 'JUPUSDT', 'JUVUSDT',
                   'KARATEUSDT', 'KASTAUSDT', 'KASUSDT', 'KAVAUSDT', 'KCALUSDT', 'KCSUSDT', 'KDAUSDT', 'KLAYUSDT', 'KMONUSDT',
                   'KOKUSDT', 'KONUSDT', 'KRLUSDT', 'KSMUSDT', 'KUBUSDT', 'KUNCIUSDT', 'LADYSUSDT', 'LDOUSDT', 'LEVERUSDT',
                   'LFWUSDT', 'LGXUSDT', 'LINGUSDT', 'LINK2LUSDT', 'LINK2SUSDT', 'LINKUSDT', 'LISUSDT', 'LMWRUSDT', 'LOOKSUSDT',
                   'LRCUSDT', 'LTC2LUSDT', 'LTC2SUSDT', 'LTCUSDT', 'LUNAUSDT', 'LUNCUSDT', 'MAGICUSDT', 'MANAUSDT', 'MANTAUSDT',
                   'MASKUSDT', 'MATIC2LUSDT', 'MATIC2SUSDT', 'MATICUSDT', 'MBOXUSDT', 'MBSUSDT', 'MBXUSDT', 'MCRTUSDT', 'MCTUSDT',
                   'MDAOUSDT', 'MEEUSDT', 'MELOSUSDT', 'MEMEUSDT', 'METHUSDT', 'MIBRUSDT', 'MINAUSDT', 'MIXUSDT', 'MKRUSDT', 'MLKUSDT',
                   'MMCUSDT', 'MNTUSDT', 'MNZUSDT', 'MOVEZUSDT', 'MOVRUSDT', 'MPLXUSDT', 'MTCUSDT', 'MTKUSDT', 'MUSDUSDT', 'MVLUSDT',
                   'MVUSDT', 'MXMUSDT', 'MXUSDT', 'MYRIAUSDT', 'MYROUSDT', 'NEARUSDT', 'NEONUSDT', 'NESSUSDT', 'NEXOUSDT', 'NEXTUSDT',
                   'NFTUSDT', 'NYMUSDT', 'OASUSDT', 'OBXUSDT', 'OKGUSDT', 'OMGUSDT', 'OMNIUSDT', 'OMNUSDT', 'ONDOUSDT', 'ONEUSDT',
                   'OPUSDT', 'ORDIUSDT', 'ORTUSDT', 'PAXGUSDT', 'PENDLEUSDT', 'PEOPLEUSDT', 'PEPE2USDT', 'PEPEUSDT', 'PERPUSDT',
                   'PIPUSDT', 'PLANETUSDT', 'PLAYUSDT', 'PLTUSDT', 'PLYUSDT', 'POKTUSDT', 'POLUSDT', 'PORT3USDT', 'PPTUSDT',
                   'PRIMALUSDT', 'PRIMEUSDT', 'PSGUSDT', 'PSPUSDT', 'PSTAKEUSDT', 'PTUUSDT', 'PUMLXUSDT', 'PYTHUSDT', 'PYUSDUSDT',
                   'QMALLUSDT', 'QNTUSDT', 'QTUMUSDT', 'RACAUSDT', 'RAINUSDT', 'RATSUSDT', 'RDNTUSDT', 'REALUSDT', 'RENUSDT',
                   'RLTMUSDT', 'RNDRUSDT', 'RONDUSDT', 'ROOTUSDT', 'ROSEUSDT', 'RPKUSDT', 'RPLUSDT', 'RSS3USDT', 'RUNEUSDT',
                   'RVNUSDT', 'SAILUSDT', 'SALDUSDT', 'SAND2LUSDT', 'SAND2SUSDT', 'SANDUSDT', 'SAROSUSDT', 'SATSUSDT', 'SCRTUSDT',
                   'SCUSDT', 'SDUSDT', 'SEILORUSDT', 'SEIUSDT', 'SEORUSDT', 'SFUNDUSDT', 'SHIBUSDT', 'SHILLUSDT', 'SHRAPUSDT',
                   'SIDUSUSDT', 'SISUSDT', 'SLGUSDT', 'SLPUSDT', 'SNXUSDT', 'SOLOUSDT', 'SOLUSDT', 'SONUSDT', 'SOSUSDT',
                   'SPARTAUSDT', 'SPELLUSDT', 'SQRUSDT', 'SRMUSDT', 'SSVUSDT', 'STATUSDT', 'STETHUSDT', 'STGUSDT', 'STRMUSDT',
                   'STXUSDT', 'SUIAUSDT', 'SUIUSDT', 'SUNUSDT', 'SUSHIUSDT', 'SWEATUSDT', 'SYNRUSDT', 'TAMAUSDT', 'TAPUSDT',
                   'TAVAUSDT', 'TELUSDT', 'TENETUSDT', 'THETAUSDT', 'THNUSDT', 'TIAUSDT', 'TIMEUSDT', 'TOKENUSDT', 'TOMIUSDT',
                   'TOMSUSDT', 'TONUSDT', 'TRCUSDT', 'TRIBEUSDT', 'TRVLUSDT', 'TRXUSDT', 'TURBOSUSDT', 'TUSDT', 'TUSDUSDT',
                   'TVKUSDT', 'TWTUSDT', 'UMAUSDT', 'UNIUSDT', 'USDCUSDT', 'USDDUSDT', 'USDYUSDT', 'USTCUSDT', 'VANRYUSDT',
                   'VEGAUSDT', 'VELAUSDT', 'VELOUSDT', 'VEXTUSDT', 'VICUSDT', 'VINUUSDT', 'VPADUSDT', 'VPRUSDT', 'VRAUSDT',
                   'VRTXUSDT', 'VVUSDT', 'WAVESUSDT', 'WAXPUSDT', 'WBTCUSDT', 'WEMIXUSDT', 'WLDUSDT', 'WLKNUSDT', 'WOOUSDT',
                   'WWYUSDT', 'XAIUSDT', 'XAVAUSDT', 'XCADUSDT', 'XDCUSDT', 'XECUSDT', 'XEMUSDT', 'XETAUSDT', 'XLMUSDT',
                   'XRP3LUSDT', 'XRP3SUSDT', 'XRPUSDT', 'XTZUSDT', 'XWGUSDT', 'XYMUSDT', 'YFIUSDT', 'ZAMUSDT', 'ZENUSDT',
                   'ZETAUSDT', 'ZIGUSDT', 'ZILUSDT', 'ZKFUSDT', 'ZRXUSDT', 'ZTXUSDT']


# session = HTTP(api_key=api_key, api_secret=api_secret, testnet=False)
#
# result = session.get_tickers(
#                 category="linear").get('result')['list']
#
# tickers = [asset['symbol'] for asset in result if asset['symbol'].endswith('USDT')]
# print(tickers)

# import requests
# a = requests.get("https://api.bybit.com/spot/v3/public/symbols")
# df = pd.DataFrame(a.json()["result"]["list"])
# trade_pairs_bybit = sorted([i for i in df["name"].values if i[-4:] == "USDT"])
# for i in trade_pairs_bybit:
#     if i == "MATICUSDT":
#         print("yes")

a = requests.get('https://api.bybit.com/spot/v3/public/quote/ticker/price?symbol=MATICUSDT')
print(a.json()["result"]["price"])