version: '3.8'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=invest
      - POSTGRES_USER=mag_user
      - POSTGRES_PASSWORD=warlight123
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/mysql/data
    restart: always

  web:
    build: .
    volumes:
      - .:/usr/src/my_djang
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: