# Generated by Django 5.0.1 on 2024-02-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name_cript', models.CharField(max_length=15, verbose_name='Название крипты')),
                ('price_buy', models.FloatField(verbose_name='Цена покупки')),
                ('price_in_1hour', models.FloatField(verbose_name='Цена за час')),
                ('price_in_2hour', models.FloatField(verbose_name='Цена за 2 часа')),
                ('price_in_3hour', models.FloatField(verbose_name='Цена за 3 часа')),
                ('price_in_5hour', models.FloatField(verbose_name='Цена за 5 часов')),
                ('price_in_24hour', models.FloatField(verbose_name='Цена за сутки')),
            ],
            options={
                'verbose_name_plural': 'Данные ордеров',
                'ordering': ('id',),
            },
        ),
    ]
