# Generated by Django 5.0.1 on 2024-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price_in_1hour',
            field=models.FloatField(null=True, verbose_name='Цена за час'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_in_24hour',
            field=models.FloatField(null=True, verbose_name='Цена за сутки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_in_2hour',
            field=models.FloatField(null=True, verbose_name='Цена за 2 часа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_in_3hour',
            field=models.FloatField(null=True, verbose_name='Цена за 3 часа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_in_5hour',
            field=models.FloatField(null=True, verbose_name='Цена за 5 часов'),
        ),
    ]
