# Generated by Django 5.0.1 on 2024-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analize', '0002_alter_orders_price_in_1hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
